# -*- coding: utf-8 -*-
"""FS with gnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFH8QRoekBEw7pGVg59wJlInoFJvm4Ge
"""

!pip install torch_geometric

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv


# ────────────────────────────────────────────────
#          GNN to model frame-level relationships
# ────────────────────────────────────────────────
class EmotionGNN(nn.Module):
    def __init__(self, in_channels=82, hidden=128, out_channels=64):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden)
        self.conv2 = GCNConv(hidden, out_channels)
        self.emotion_head = nn.Linear(out_channels, 4)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        x = self.conv2(x, edge_index)
        pooled = x.mean(dim=0)
        emotion_logits = self.emotion_head(pooled)
        return x, emotion_logits


# ────────────────────────────────────────────────
#         Simple Emotional TTS
# ────────────────────────────────────────────────
class SimpleEmotionalTTS(nn.Module):
    def __init__(self, mel_dim=80, emotion_dim=32, nhead=4, num_layers=2):
        super().__init__()

        self.gnn = EmotionGNN(in_channels=mel_dim + 2, out_channels=64)

        self.variance_adaptor = nn.Sequential(
            nn.Linear(64, mel_dim),
            nn.ReLU(),
        )

        self.emotion_proj = nn.Linear(emotion_dim, mel_dim)
        self.emotion_emb = nn.Embedding(4, emotion_dim)

        self.decoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=mel_dim,
                nhead=nhead,
                dim_feedforward=mel_dim * 4,
                dropout=0.1,
                batch_first=True
            ),
            num_layers=num_layers
        )

        self.mel_head = nn.Linear(mel_dim, mel_dim)

    def forward(self, phoneme_features, edge_index, emotion_label):

        gnn_out, emotion_logits = self.gnn(phoneme_features, edge_index)

        adapted = self.variance_adaptor(gnn_out)

        emo_vec = self.emotion_emb(emotion_label)
        emo_vec = self.emotion_proj(emo_vec)

        adapted = adapted + emo_vec  # broadcast

        adapted = adapted.unsqueeze(0)

        decoded = self.decoder(adapted)
        decoded = decoded.squeeze(0)

        mel_pred = self.mel_head(decoded)

        return mel_pred, emotion_logits


# ────────────────────────────────────────────────
#                    Training Demo
# ────────────────────────────────────────────────
def main():
    torch.manual_seed(42)

    model = SimpleEmotionalTTS(mel_dim=80)
    model.train()

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

    # ─── Dummy input ─────────────────────────────────────
    num_frames = 73

    features = torch.randn(num_frames, 82)

    # ✅ FIXED EDGE INDEX
    src = torch.arange(0, num_frames - 1)
    dst = torch.arange(1, num_frames)
    edge_index = torch.stack([src, dst], dim=0)

    emotion_label = torch.tensor([0])

    target_mel = torch.randn(num_frames, 80)

    print("Starting dummy training loop...\n")

    for epoch in range(10):
        optimizer.zero_grad()

        mel_pred, emo_logits = model(features, edge_index, emotion_label)

        loss_mel = F.mse_loss(mel_pred, target_mel)
        loss_emo = F.cross_entropy(emo_logits.unsqueeze(0), emotion_label)

        loss_total = loss_mel + 0.5 * loss_emo

        loss_total.backward()
        optimizer.step()

        print(f"Epoch {epoch:2d} | "
              f"mel = {loss_mel:.4f}   "
              f"emo = {loss_emo:.4f}   "
              f"total = {loss_total:.4f}")

    print("\nTraining finished. No shape errors → model runs correctly.")


if __name__ == "__main__":
    main()

# Commented out IPython magic to ensure Python compatibility.
# ====================== FULL SETUP FOR COLAB ======================
!git clone https://github.com/keonlee9420/Expressive-FastSpeech2.git
# %cd Expressive-FastSpeech2

# Install requirements
!pip install -r requirements.txt

# Install torch-geometric correctly for Colab
import torch
print("PyTorch:", torch.__version__)

!pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-{torch.__version__.split('+')[0]}+cu121.html

# Extra libraries
!pip install whisper openai-whisper librosa pyworld soundfile transformers torchaudio pyngrok

print("✅ Repo cloned and all packages installed!")

!pip install sys
import sys
sys.path.append('/content/Expressive-FastSpeech2')

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv, global_mean_pool
import whisper
import librosa
import numpy as np
import soundfile as sf
import pyworld as pw
from transformers import pipeline
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# ====================== GNN for Emotion Disentanglement ======================
class EmotionDisentangleGNN(nn.Module):
    def __init__(self, input_dim=3, hidden_dim=64, emotion_dim=32):
        super().__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.conv3 = GCNConv(hidden_dim, emotion_dim)
        self.emotion_head = nn.Linear(emotion_dim, 5)

    def forward(self, x, edge_index, batch):
        x = F.relu(self.conv1(x, edge_index))
        x = F.relu(self.conv2(x, edge_index))
        x = self.conv3(x, edge_index)
        emotion_emb = global_mean_pool(x, batch)
        emotion_pred = self.emotion_head(emotion_emb)
        return emotion_emb, emotion_pred

gnn = EmotionDisentangleGNN().to(device)
gnn.eval()

# Load ASR + Emotion Classifier
asr = whisper.load_model("base")
emotion_classifier = pipeline("audio-classification", model="superb/hubert-large-superb-er", device=0 if torch.cuda.is_available() else -1)

print("✅ Whisper, GNN, Emotion classifier loaded")

from model.fastspeech2 import FastSpeech2
from hifigan.models import Generator
!pip install wget unidecode
import wget

# ====================== FastSpeech2 and HiFi-GAN ======================

fs2 = FastSpeech2().to(device)
hifigan = Generator().to(device)

# NOTE: You need a checkpoint for good quality
# For now we use random weights (output will be noisy).
# Later download/train and load like this:
# ckpt = torch.load("path_to_checkpoint.pth", map_location=device)
# fs2.load_state_dict(ckpt["model"] if "model" in ckpt else ckpt)

print("✅ FastSpeech2 and HiFi-GAN loaded (random weights for now)")

# ====================== Prosody Analysis ======================
def analyze_prosody(audio_path):
    y, sr = librosa.load(audio_path, sr=22050)
    f0, _, _ = librosa.pyin(y, fmin=librosa.note_to_hz('C2'), fmax=librosa.note_to_hz('C7'))
    pitch = np.nanmean(f0) if f0 is not None and not np.all(np.isnan(f0)) else 0.0
    rms = librosa.feature.rms(y=y)[0]
    energy = float(np.mean(rms))
    silence_ratio = float(np.sum(rms < 0.01) / len(rms))
    duration = float(len(y) / sr)
    return {
        "pitch_mean": pitch,
        "energy_mean": energy,
        "silence_ratio": silence_ratio,
        "duration_sec": duration,
        "raw_audio": y,
        "sr": sr
    }

print("✅ All functions ready")

def main(input_audio_path, target_emotion="angry", output_path="output_emotion.wav"):
    if not os.path.exists(input_audio_path):
        print("❌ Input audio file not found!")
        return

    print("🚀 Processing...")

    # Input Analysis
    analysis = analyze_prosody(input_audio_path)
    print("\n📊 INPUT AUDIO ANALYSIS:")
    print(f"Pitch     : {analysis['pitch_mean']:.1f} Hz")
    print(f"Energy    : {analysis['energy_mean']:.4f}")
    print(f"Silence   : {analysis['silence_ratio']:.1%}")
    print(f"Duration  : {analysis['duration_sec']:.2f} sec")

    # Transcribe text
    text = asr.transcribe(input_audio_path)["text"]
    print(f"\n📝 Transcribed Text: {text}")

    # Reference emotion
    ref_emo = emotion_classifier(input_audio_path)[0]['label']
    print(f"Detected emotion in input: {ref_emo}")

    # Prepare prosody for GNN
    y, sr = analysis["raw_audio"], analysis["sr"]
    f0 = pw.harvest(y.astype(np.float64), sr)[0]
    energy = librosa.feature.rms(y=y)[0]
    num_frames = len(f0)
    if num_frames < 2:
        print("❌ Audio too short!")
        return

    duration_norm = np.full(num_frames, analysis["duration_sec"] / num_frames)
    prosody_seq = np.stack([f0, energy, duration_norm], axis=1).astype(np.float32)

    # Graph for GNN
    edge_list = [[i, i+1] for i in range(num_frames-1)] + [[i+1, i] for i in range(num_frames-1)]
    edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous().to(device)
    batch = torch.zeros(num_frames, dtype=torch.long).to(device)
    prosody_tensor = torch.from_numpy(prosody_seq).to(device)

    with torch.no_grad():
        emotion_emb, _ = gnn(prosody_tensor, edge_index, batch)

    print(f"✅ GNN disentangled emotion embedding ready")

    # Emotion ID
    emo_map = {"neutral": 0, "happy": 1, "angry": 2, "sad": 3, "surprise": 4}
    emo_id = emo_map.get(target_emotion.lower(), 0)

    print(f"🎯 Generating with target emotion: **{target_emotion.upper()}**")

    # TODO: Real synthesis (adapt from evaluate.py)
    # For demo we generate dummy output
    # In real use: mel = fs2(...) with emo_id and emotion_emb
    dummy_mel = torch.randn(1, 80, 300).to(device)  # placeholder

    with torch.no_grad():
        wav = hifigan(dummy_mel.transpose(1, 2)).squeeze().cpu().numpy()

    sf.write(output_path, wav, 22050)
    print(f"\n✅ Audio saved as: {output_path}")

    # Output Analysis
    gen_analysis = analyze_prosody(output_path)
    print("\n📊 GENERATED AUDIO ANALYSIS:")
    print(f"Pitch     : {gen_analysis['pitch_mean']:.1f} Hz")
    print(f"Energy    : {gen_analysis['energy_mean']:.4f}")
    print(f"Silence   : {gen_analysis['silence_ratio']:.1%}")
    print(f"Duration  : {gen_analysis['duration_sec']:.2f} sec")
    print("\n🎉 Done! (Note: Current output is placeholder because no checkpoint loaded)")

# ====================== RUN EXAMPLE ======================
# Upload your audio first in Colab (left sidebar → Files → Upload)
# Then run:
main("/content/your_input_audio.wav", target_emotion="angry", output_path="/content/angry_output.wav")