# -*- coding: utf-8 -*-
"""assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kFEInPHVSL8ZgexkRnVhwimCbMdh1Nj
"""

# SPOOF AUDIO GENERATION WITH SPEECHT5 + EMOTION SIMULATION


import sys, os, subprocess

#  1. Install dependencies
print(" Installing required packages...")
!pip install -q torch torchaudio transformers soundfile pandas datasets speechbrain pyrubberband

# Install rubberband-cli (needed for pitch/time modification)
if os.name == "posix":
    try:
        !apt-get update -qq && apt-get install -y -qq rubberband-cli
    except Exception as e:
        print(f" Could not install rubberband-cli: {e} (may already be present)")

# 2. Imports
import torch
import torchaudio
import soundfile as sf
import numpy as np
from scipy.spatial.distance import cosine
from transformers import SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan
from speechbrain.inference.speaker import EncoderClassifier

# Try importing pyrubberband; if it fails, we'll skip emotion modifications
try:
    import pyrubberband as pyrb
    RUBBERBAND_AVAILABLE = True
except ImportError:
    RUBBERBAND_AVAILABLE = False
    print(" pyrubberband not available. Emotion simulation will be disabled (neutral only).")

#  3. Extract YOUR speaker embedding
YOUR_AUDIO_FILE = "/content/04-10-2026 13.55.wav"
print(f"\n🔊 Extracting your speaker embedding from:\n   {YOUR_AUDIO_FILE}")

classifier_ecapa = EncoderClassifier.from_hparams(
    source="speechbrain/spkrec-ecapa-voxceleb",
    savedir="tmp_ecapa"
)

def extract_speaker_embedding(audio_path, target_dim=512):
    if not os.path.exists(audio_path):
        raise FileNotFoundError(f"Audio file not found: {audio_path}")
    signal, fs = torchaudio.load(audio_path)
    if fs != 16000:
        print(f"   Resampling from {fs} Hz to 16000 Hz")
        resampler = torchaudio.transforms.Resample(fs, 16000)
        signal = resampler(signal)
    # signal shape: [channels, samples] -> make it mono if needed
    if signal.shape[0] > 1:
        signal = torch.mean(signal, dim=0, keepdim=True)
    # ECAPA encode_batch expects shape [batch, time] -> [1, time]
    embedding = classifier_ecapa.encode_batch(signal)  # [1, 1, 192]
    emb = embedding.squeeze()  # squeeze all dims -> [192] or scalar if empty
    if emb.dim() == 0:
        raise ValueError("Embedding extraction failed; got scalar.")
    # Pad to target_dim
    if emb.shape[0] < target_dim:
        emb = torch.nn.functional.pad(emb, (0, target_dim - emb.shape[0]))
    else:
        emb = emb[:target_dim]
    # Ensure shape is [1, target_dim] for SpeechT5
    return emb.unsqueeze(0)  # [1, 512]

try:
    my_embedding = extract_speaker_embedding(YOUR_AUDIO_FILE)
    print(f"Your embedding extracted! Shape: {my_embedding.shape}")
except FileNotFoundError as e:
    print(f"\n {e}")
    print("   Using a random embedding for demonstration.")
    my_embedding = torch.randn(1, 512)
except Exception as e:
    print(f" Unexpected error: {e}")
    print("   Using a random embedding for demonstration.")
    my_embedding = torch.randn(1, 512)

#  4. Load SpeechT5 models
print("\n Loading SpeechT5 models...")
processor = SpeechT5Processor.from_pretrained("microsoft/speecht5_tts")
model = SpeechT5ForTextToSpeech.from_pretrained("microsoft/speecht5_tts")
vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan")
print(" Models loaded.")

#  5. Emotion simulation function -
def generate_emotional_speech(text, speaker_emb, emotion="neutral", output_path=None):
    """
    Generate speech with the given speaker embedding,
    then apply pitch & speed changes to simulate emotion (if pyrubberband available).
    """
    inputs = processor(text=text, return_tensors="pt")
    with torch.no_grad():
        speech = model.generate_speech(
            inputs["input_ids"],
            speaker_emb,  # already shape [1, 512]
            vocoder=vocoder
        )
    speech_np = speech.squeeze().cpu().numpy()
    sr = 16000

    # Emotion presets
    presets = {
        "neutral":  (0.0, 1.0),
        "happy":    (+2.0, 1.15),
        "sad":      (-2.5, 0.85),
        "angry":    (+1.5, 1.05),
        "excited":  (+4.0, 1.25),
        "calm":     (-1.0, 0.95)
    }
    pitch_shift, speed_factor = presets.get(emotion, (0.0, 1.0))

    if emotion != "neutral" and RUBBERBAND_AVAILABLE:
        try:
            speech_mod = pyrb.pitch_shift(speech_np, sr, n_steps=pitch_shift)
            speech_mod = pyrb.time_stretch(speech_mod, sr, speed_factor)
        except Exception as e:
            print(f"    pyrubberband failed: {e}. Using neutral output.")
            speech_mod = speech_np
    else:
        speech_mod = speech_np

    if output_path:
        sf.write(output_path, speech_mod, sr)
    return speech_mod, sr

print("🎭 Emotion simulation ready." if RUBBERBAND_AVAILABLE else "🎭 Emotion simulation disabled (fallback to neutral).")

#  6. Generate 15 spoofed samples
print("\n🎤 Generating 15 emotional spoof samples...")

# Fixed text for all samples
fixed_text = "Hello, this is my voice speaking with different emotions."

# Emotions to cycle through (5 emotions × 3 repetitions = 15 samples)
emotions = ["calm", "happy", "sad", "angry", "excited"] * 3

# Create the list of (text, emotion) tuples
texts_emotions = [(fixed_text, emotion) for emotion in emotions]

#  Shuffle or verify length
assert len(texts_emotions) == 15
print(f"Created {len(texts_emotions)} samples with the same text and varying emotions.")
generated_files = []
for i, (text, emotion) in enumerate(texts_emotions):
    fname = f"spoof_sample_{i:02d}_{emotion}.wav"
    generate_emotional_speech(text, my_embedding, emotion=emotion, output_path=fname)
    generated_files.append(fname)
    print(f"   {fname}")

print(f"🎉 Generated {len(generated_files)} samples.")

#  7. Evaluation
print("\n Evaluating spoof samples...")

def get_embedding(file_path):
    signal, fs = torchaudio.load(file_path)
    if fs != 16000:
        resampler = torchaudio.transforms.Resample(fs, 16000)
        signal = resampler(signal)
    if signal.shape[0] > 1:
        signal = torch.mean(signal, dim=0, keepdim=True)
    emb = classifier_ecapa.encode_batch(signal).squeeze()
    if emb.dim() == 0:
        return np.zeros(512)
    if emb.shape[0] < 512:
        emb = torch.nn.functional.pad(emb, (0, 512 - emb.shape[0]))
    else:
        emb = emb[:512]
    return emb.numpy()

ref_emb = my_embedding.squeeze().numpy()
similarities = []
accept_count = 0
threshold = 0.25  # cosine distance threshold

print("Sample Similarities (cosine):")
for fname in generated_files:
    spoof_emb = get_embedding(fname)
    sim = 1 - cosine(spoof_emb, ref_emb)
    similarities.append(sim)
    dist = 1 - sim
    accepted = dist < threshold
    if accepted:
        accept_count += 1
    status = "ACCEPT" if accepted else " REJECT"
    print(f"  {fname:30} similarity = {sim:.3f}  {status}")

avg_sim = np.mean(similarities)
spoof_success_rate = accept_count / len(generated_files)

print("\n" + "="*50)
print(f" Average Speaker Similarity : {avg_sim:.3f}")
print(f" Spoof Success Rate        : {spoof_success_rate*100:.1f}% ({accept_count}/{len(generated_files)})")
print("="*50)

from IPython.display import Audio, display
import os

print("\n" + "="*60)
print("AUDIO PLAYBACK")
print("="*60)

# Display input file (user's voice)
input_file = "/content/04-10-2026 13.55.wav"
if os.path.exists(input_file):
    print("\n🎤 YOUR VOICE INPUT:")
    display(Audio(input_file))
else:
    print("\n Input file not found. Please upload your audio.")

# Display first 5 generated spoof samples
print("\n GENERATED SPOOF SAMPLES (first 5):")
for i in range(5):
    fname = f"spoof_sample_{i:02d}_*.wav"
    # Since we don't know exact emotion suffix, find the matching file
    import glob
    matches = glob.glob(f"spoof_sample_{i:02d}_*.wav")
    if matches:
        fname = matches[0]
        # Extract emotion from filename
        emotion = fname.split('_')[-1].replace('.wav', '')
        print(f"\nSample {i+1} - Emotion: {emotion}")
        display(Audio(fname))
    else:
        print(f"\nSample {i+1} not found.")

#EVALUATION CELL

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import librosa
import soundfile as sf
import torch
import torchaudio
from scipy.spatial.distance import cosine
from IPython.display import Audio, display

#  Helper: Compute MCD (Mel Cepstral Distortion)
def compute_mcd(audio1, audio2, sr=16000, n_mfcc=13):
    """
    Compute MCD between two audio signals.
    Audio1: reference (your original voice)
    Audio2: spoofed sample
    """
    try:
        mfcc1 = librosa.feature.mfcc(y=audio1, sr=sr, n_mfcc=n_mfcc)
        mfcc2 = librosa.feature.mfcc(y=audio2, sr=sr, n_mfcc=n_mfcc)
        # Align to the shorter sequence
        min_len = min(mfcc1.shape[1], mfcc2.shape[1])
        mfcc1 = mfcc1[:, :min_len]
        mfcc2 = mfcc2[:, :min_len]
        diff = np.sqrt(np.sum((mfcc1 - mfcc2) ** 2, axis=0))
        return float(np.mean(diff))
    except Exception as e:
        print(f"    MCD computation failed: {e}")
        return 99.0

# Load your original voice as reference for MCD
ref_audio_path = "/content/04-10-2026 13.55.wav"
if os.path.exists(ref_audio_path):
    ref_audio, ref_sr = torchaudio.load(ref_audio_path)
    if ref_sr != 16000:
        resampler = torchaudio.transforms.Resample(ref_sr, 16000)
        ref_audio = resampler(ref_audio)
    ref_audio_np = ref_audio.squeeze().numpy()
else:
    print(" Reference audio not found; MCD values will be computed against a silent dummy.")
    ref_audio_np = np.zeros(16000)

# Gather all generated spoof files
generated_files = sorted([f for f in os.listdir() if f.startswith("spoof_sample_") and f.endswith(".wav")])
if not generated_files:
    raise FileNotFoundError("No spoof_sample_*.wav files found. Run the generation cell first.")

print(f"Found {len(generated_files)} spoof samples.")

#  Extract embeddings and compute metrics
# Reuse classifier from previous cell (assumes it's still in memory)
try:
    classifier_ecapa
except NameError:
    print(" Speaker classifier not found; re‑loading.")
    from speechbrain.inference.speaker import EncoderClassifier
    classifier_ecapa = EncoderClassifier.from_hparams(
        source="speechbrain/spkrec-ecapa-voxceleb",
        savedir="tmp_ecapa"
    )

def get_embedding(file_path):
    signal, fs = torchaudio.load(file_path)
    if fs != 16000:
        resampler = torchaudio.transforms.Resample(fs, 16000)
        signal = resampler(signal)
    if signal.shape[0] > 1:
        signal = torch.mean(signal, dim=0, keepdim=True)
    emb = classifier_ecapa.encode_batch(signal).squeeze()
    if emb.dim() == 0:
        return np.zeros(512)
    if emb.shape[0] < 512:
        emb = torch.nn.functional.pad(emb, (0, 512 - emb.shape[0]))
    else:
        emb = emb[:512]
    return emb.numpy()

# Reference embedding
try:
    ref_emb = my_embedding.squeeze().numpy()
except NameError:
    print("Reference embedding not found; extracting from reference audio.")
    ref_emb = get_embedding(ref_audio_path)

# Build evaluation dataframe
eval_data = []
for i, fname in enumerate(generated_files):
    # Extract emotion from filename (e.g., spoof_sample_00_calm.wav → calm)
    parts = fname.replace('.wav', '').split('_')
    emotion = parts[-1] if len(parts) >= 4 else "unknown"

    # Load audio
    audio, sr = sf.read(fname)
    if sr != 16000:
        audio = librosa.resample(audio, orig_sr=sr, target_sr=16000)

    # Speaker similarity
    emb = get_embedding(fname)
    sim = 1 - cosine(emb, ref_emb)

    # MCD (compare to reference voice – note: content differs, so MCD is only indicative)
    # Trim reference audio to same length for comparison
    min_len = min(len(audio), len(ref_audio_np))
    mcd = compute_mcd(ref_audio_np[:min_len], audio[:min_len])

    # Peak amplitude
    peak = np.max(np.abs(audio))

    # Guess emotion modifier (we stored mapping earlier; if not available, use neutral)
    # We'll set a default based on emotion name
    emotion_mod_map = {
        "calm": 0.85, "excited": 1.20, "sad": 0.80, "angry": 1.10, "happy": 1.15, "neutral": 1.00
    }
    emotion_mod = emotion_mod_map.get(emotion, 1.0)

    eval_data.append({
        'file': fname,
        'emotion': emotion,
        'emotion_modifier': emotion_mod,
        'speaker_similarity': sim,
        'mcd': mcd,
        'peak_amplitude': peak
    })

df_eval = pd.DataFrame(eval_data)

# Summary Statistics
print("\n" + "="*60)
print("EVALUATION STATISTICS")
print("="*60)
print(df_eval[['speaker_similarity', 'mcd', 'peak_amplitude']].describe().round(3))

# Spoof success rate (similarity threshold 0.7, peak > 0.01)
threshold_sim = 0.7
spoof_accepted = df_eval[(df_eval['speaker_similarity'] > threshold_sim) & (df_eval['peak_amplitude'] > 0.01)]
success_rate = len(spoof_accepted) / len(df_eval) * 100
print(f"\n Spoof Success Rate (similarity > {threshold_sim}): {success_rate:.1f}% ({len(spoof_accepted)}/{len(df_eval)})")

# Plots
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 1. Placeholder for training loss (SpeechT5 is pretrained – we show a note)
axes[0,0].text(0.5, 0.5, "SpeechT5 is a pretrained model\n(no training loss available)",
               ha='center', va='center', fontsize=12, transform=axes[0,0].transAxes)
axes[0,0].set_title("Training Loss (N/A – Pretrained Model)")

# 2. Speaker Similarity Histogram
axes[0,1].hist(df_eval['speaker_similarity'], bins=10, color='skyblue', edgecolor='black', alpha=0.7)
axes[0,1].axvline(threshold_sim, color='red', linestyle='--', label=f'Threshold {threshold_sim}')
axes[0,1].set_title("Speaker Similarity Distribution")
axes[0,1].set_xlabel("Cosine Similarity")
axes[0,1].set_ylabel("Count")
axes[0,1].legend()
axes[0,1].grid(alpha=0.3)

# 3. MCD Bar Chart
axes[1,0].bar(range(len(df_eval)), df_eval['mcd'], color='coral', edgecolor='black', alpha=0.7)
axes[1,0].axhline(df_eval['mcd'].mean(), color='red', linestyle='--', label=f"Mean MCD = {df_eval['mcd'].mean():.2f}")
axes[1,0].set_title("Mel Cepstral Distortion (MCD) by Sample")
axes[1,0].set_xlabel("Sample Index")
axes[1,0].set_ylabel("MCD")
axes[1,0].legend()
axes[1,0].grid(alpha=0.3)

# 4. Emotion Modifier vs. Similarity Scatter (color = peak amplitude)
sc = axes[1,1].scatter(df_eval['emotion_modifier'], df_eval['speaker_similarity'],
                       c=df_eval['peak_amplitude'], cmap='viridis', s=80, edgecolor='k')
plt.colorbar(sc, ax=axes[1,1], label='Peak Amplitude')
axes[1,1].set_title("Emotion Modifier vs. Speaker Similarity")
axes[1,1].set_xlabel("Emotion Modifier (Pitch/Speed Factor)")
axes[1,1].set_ylabel("Speaker Similarity")
axes[1,1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("spoof_evaluation_plots.png", dpi=150)
plt.show()
print(" Plots saved as 'spoof_evaluation_plots.png'")

#  Audio Playback
print("\n" + "="*60)
print(" AUDIO PLAYBACK (First 5 Spoof Samples)")
print("="*60)
for i in range(min(5, len(df_eval))):
    row = df_eval.iloc[i]
    print(f"\n {row['file']}")
    print(f"   Emotion: {row['emotion'].upper()} | Similarity: {row['speaker_similarity']:.3f} | MCD: {row['mcd']:.2f}")
    display(Audio(row['file']))

print("\n Evaluation complete.")

#Independent cell: Store all generated output in one file


import zipfile
import os
import pandas as pd
from google.colab import files

# Ensure 'generated_files' list exists from previous cell
if 'generated_files' not in dir() or not generated_files:
    raise RuntimeError("No generated_files found. Please run the generation cell first.")

# Create a metadata table
metadata = []
for fname in generated_files:
    # Extract emotion from filename (e.g., 'spoof_sample_00_calm.wav' -> 'calm')
    emotion = fname.split('_')[-1].replace('.wav', '')
    metadata.append({'filename': fname, 'emotion': emotion})

df_meta = pd.DataFrame(metadata)

# Save metadata CSV
meta_csv = 'spoof_metadata.csv'
df_meta.to_csv(meta_csv, index=False)

# Create a single ZIP archive containing all files
zip_name = 'spoof_audio_collection.zip'
with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
    # Add all generated audio files
    for fname in generated_files:
        zipf.write(fname, arcname=os.path.basename(fname))
    # Add the metadata CSV
    zipf.write(meta_csv)

print(f" All outputs stored in: {zip_name}")
print(f"   Contains {len(generated_files)} WAV files + metadata CSV.")

# Download the zip file (works in Google Colab)
files.download(zip_name)